# Generated by Django 3.1.1 on 2020-10-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255)),
                ('files', models.FileField(blank=True, upload_to='memo_images_first_section/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255)),
                ('files', models.FileField(blank=True, upload_to='memo_images_second_section/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255)),
                ('files', models.FileField(blank=True, upload_to='memo_images_third_section/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('brand_desc', models.CharField(max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/%Y/%m/%d')),
                ('tab01', models.CharField(default='Tab #1', max_length=50)),
                ('tab02', models.CharField(default='Tab #2', max_length=50)),
                ('tab03', models.CharField(default='Tab #3', max_length=50)),
                ('tab04', models.CharField(default='Tab #4', max_length=50)),
                ('tab05', models.CharField(default='Tab #5', max_length=50)),
                ('tab06', models.CharField(default='TRASH', max_length=50)),
                ('tab_view', models.CharField(default='on', max_length=50)),
                ('tab_theme', models.CharField(default='study', max_length=50)),
                ('view_mode', models.CharField(default='media', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_code', models.TextField(null=True)),
                ('language', models.TextField(max_length=30, null=True)),
                ('desc', models.TextField(null=True)),
                ('image01', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image02', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image03', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image04', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('style_first', models.CharField(max_length=255, null=True)),
                ('image05', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image06', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image07', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image08', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('style_second', models.CharField(max_length=255, null=True)),
                ('image09', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('style_third', models.CharField(max_length=255, null=True)),
                ('subject_2nd', models.CharField(max_length=255, null=True)),
                ('content_2nd', models.TextField(null=True)),
                ('desc_2nd', models.TextField(null=True)),
                ('subject_3rd', models.CharField(max_length=255, null=True)),
                ('content_3rd', models.TextField(null=True)),
                ('desc_3rd', models.TextField(null=True)),
                ('video01', models.TextField(null=True)),
                ('video02', models.TextField(null=True)),
                ('video03', models.TextField(null=True)),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('tab_name', models.CharField(max_length=20, null=True)),
                ('disclose', models.CharField(default='public', max_length=20)),
                ('comment_on', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='memo.users')),
                ('users', models.ManyToManyField(related_name='saved', to='memo.Users')),
            ],
        ),
        migrations.CreateModel(
            name='DMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_id', models.CharField(max_length=255, null=True)),
                ('from_user_id', models.CharField(max_length=255, null=True)),
                ('dm_msg', models.TextField(null=True)),
                ('if_to_checked', models.CharField(default='no', max_length=5)),
                ('if_to_reply_checked', models.CharField(default='no', max_length=5)),
                ('if_from_reply_checked', models.CharField(default='yes', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_sent_by', to='memo.users')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm', to='memo.users')),
            ],
        ),
        migrations.CreateModel(
            name='DmReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_dm_id', models.CharField(max_length=255)),
                ('reply_user_id', models.CharField(max_length=255)),
                ('reply_name', models.CharField(max_length=255)),
                ('reply_msg', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_reply', to='memo.dms')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('reply_by_profile_pic', models.CharField(max_length=255, null=True)),
                ('reply_by_dashboard', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='memo.memos')),
            ],
        ),
    ]
