# Generated by Django 3.1.1 on 2020-10-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
