# Generated by Django 3.1.2 on 2020-10-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_memos_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memos',
            name='if_new_comment',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='memos',
            name='new_comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='view_mode',
            field=models.CharField(default='social media mode', max_length=50),
        ),
    ]
